from __future__ import annotations
from pathlib import Path
import guitarpro
from guitarpro import models
from music_theory import chord_shape, normalize_chord, strumming_pattern, transpose_chord

def _ensure_measures(song, count, meter="4/4"):
    while len(song.measureHeaders) < count:
        song.newMeasure()
    num,den=[int(x) for x in meter.split("/")]
    for i,h in enumerate(song.measureHeaders[:count]):
        h.number=i+1
        h.timeSignature=models.TimeSignature(num, models.Duration(den))
        if i==0:
            h.start=models.Duration.quarterTime
        else:
            h.start=song.measureHeaders[i-1].end

def _add_chord_beat(voice, start, duration_value, chord, direction=None, rest=False):
    beat=models.Beat(voice)
    beat.start=start
    beat.duration=models.Duration(duration_value)
    if rest:
        beat.status=models.BeatStatus.rest
    else:
        beat.status=models.BeatStatus.normal
        c=normalize_chord(chord)
        shape=chord_shape(c)  # low->high
        # Store the chord name as beat text. This is robust across GP5 readers
        # and keeps the actual tablature notes on the staff/tab.
        beat.text=c
        if direction=="d":
            beat.effect.stroke.direction=models.BeatStrokeDirection.down
        elif direction=="u":
            beat.effect.stroke.direction=models.BeatStrokeDirection.up
        # track string 1 is high E, so reverse standard shape
        for string_num,fret in enumerate(reversed(shape), start=1):
            if fret >= 0:
                note=models.Note(beat, value=int(fret), string=string_num, type=models.NoteType.normal)
                beat.notes.append(note)
    voice.beats.append(beat)

def build_arrangement_gp5(chords, bpm, meter, out_path, style="strum", title="Guitar AI Arrangement", capo=0):
    chords=[normalize_chord(c) for c in chords if c]
    if not chords: raise ValueError("No chords")
    capo=max(0,min(12,int(capo or 0)))
    tab_chords=[transpose_chord(c,-capo) for c in chords] if capo else list(chords)
    song=models.Song()
    song.title=title
    song.artist="Generated by Guitar AI Assistant"
    song.tempo=max(30,min(260,int(round(float(bpm)))))
    song.tempoName="Practice"
    song.tracks[0].name="Rhythm Guitar" + (f" — Capo {capo}" if capo else "")
    song.tracks[0].offset=capo
    song.instructions=(f"Capo: fret {capo}. Chord names in tablature are the shapes to play." if capo else "No capo.")
    song.tracks[0].channel.instrument=25
    song.tracks[0].settings.showRhythm=True
    _ensure_measures(song,len(chords),meter)
    pattern=strumming_pattern(float(bpm),meter,style)
    # We use equal subdivisions that fill one bar.
    if meter=="4/4":
        dur=models.Duration.eighth
        slots=8
    elif meter in ("3/4","6/8"):
        dur=models.Duration.eighth
        slots=6
    else:
        dur=models.Duration.eighth
        slots=8
    dir_by_step={s:d for s,d in pattern["steps"]}
    for mi,chord in enumerate(tab_chords):
        measure=song.tracks[0].measures[mi]
        voice=measure.voices[0]
        voice.beats.clear()
        step_time=models.Duration(dur).time
        for step in range(slots):
            start=measure.start + step*step_time
            direction=dir_by_step.get(step)
            _add_chord_beat(voice,start,dur,chord,direction=direction,rest=(direction is None))
    guitarpro.write(song,out_path,version=(5,1,0))
    return out_path

def midi_note_to_string_fret(midi_note, used_strings=None, prev_fret=5):
    tuning=[64,59,55,50,45,40]  # string 1..6
    used_strings=used_strings or set()
    choices=[]
    for s,open_note in enumerate(tuning,start=1):
        fret=midi_note-open_note
        if 0 <= fret <= 24 and s not in used_strings:
            choices.append((abs(fret-prev_fret)+0.12*fret,s,fret))
    if not choices:
        return None
    _,s,fret=min(choices)
    return s,int(fret)

def build_tab_from_midi(midi_path, bpm, out_path, title="Video Transcription", max_seconds=180):
    import pretty_midi
    pm=pretty_midi.PrettyMIDI(midi_path)
    notes=[]
    for inst in pm.instruments:
        if inst.is_drum: continue
        notes.extend(inst.notes)
    notes=[n for n in notes if n.start <= max_seconds]
    notes.sort(key=lambda n:n.start)
    bpm=max(40,min(240,float(bpm or 120)))
    sixteenth=60.0/bpm/4.0
    slots={}
    for n in notes:
        idx=int(round(n.start/sixteenth))
        slots.setdefault(idx,[]).append(n.pitch)
    max_slot=max(slots.keys(),default=0)
    measures=max(1,max_slot//16+1)

    song=models.Song()
    song.title=title
    song.artist="Automatic transcription — verify by ear"
    song.tempo=int(round(bpm))
    song.tracks[0].name="Detected Guitar"
    song.tracks[0].channel.instrument=25
    _ensure_measures(song,measures,"4/4")
    prev_fret=5
    for mi in range(measures):
        measure=song.tracks[0].measures[mi]
        voice=measure.voices[0]; voice.beats.clear()
        for local in range(16):
            idx=mi*16+local
            beat=models.Beat(voice)
            beat.start=measure.start + local*models.Duration(models.Duration.sixteenth).time
            beat.duration=models.Duration(models.Duration.sixteenth)
            pitches=sorted(set(slots.get(idx,[])))
            if pitches:
                beat.status=models.BeatStatus.normal
                used=set()
                for pitch in pitches[:6]:
                    sf=midi_note_to_string_fret(pitch,used,prev_fret)
                    if sf:
                        s,f=sf; used.add(s); prev_fret=f
                        beat.notes.append(models.Note(beat,value=f,string=s,type=models.NoteType.normal))
            else:
                beat.status=models.BeatStatus.rest
            voice.beats.append(beat)
    guitarpro.write(song,out_path,version=(5,1,0))
    return out_path
