from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path
import math
import guitarpro
from guitarpro import models
from music_theory import chord_shape, normalize_chord, strumming_pattern, transpose_chord

# Standard tuning, Guitar Pro string numbers 1..6 (high E -> low E)
TUNING = [64, 59, 55, 50, 45, 40]


def _ensure_measures(song, count, meter="4/4"):
    while len(song.measureHeaders) < count:
        song.newMeasure()
    num, den = [int(x) for x in meter.split("/")]
    for i, h in enumerate(song.measureHeaders[:count]):
        h.number = i + 1
        h.timeSignature = models.TimeSignature(num, models.Duration(den))
        if i == 0:
            h.start = models.Duration.quarterTime
        else:
            h.start = song.measureHeaders[i - 1].end


def _add_chord_beat(voice, start, duration_value, chord, direction=None, rest=False):
    beat = models.Beat(voice)
    beat.start = start
    beat.duration = models.Duration(duration_value)
    if rest:
        beat.status = models.BeatStatus.rest
    else:
        beat.status = models.BeatStatus.normal
        c = normalize_chord(chord)
        shape = chord_shape(c)
        beat.text = c
        if direction == "d":
            beat.effect.stroke.direction = models.BeatStrokeDirection.down
        elif direction == "u":
            beat.effect.stroke.direction = models.BeatStrokeDirection.up
        for string_num, fret in enumerate(reversed(shape), start=1):
            if fret >= 0:
                beat.notes.append(
                    models.Note(beat, value=int(fret), string=string_num, type=models.NoteType.normal)
                )
    voice.beats.append(beat)


def build_arrangement_gp5(chords, bpm, meter, out_path, style="strum", title="Guitar AI Arrangement", capo=0):
    chords = [normalize_chord(c) for c in chords if c]
    if not chords:
        raise ValueError("No chords")
    capo = max(0, min(12, int(capo or 0)))
    tab_chords = [transpose_chord(c, -capo) for c in chords] if capo else list(chords)
    song = models.Song()
    song.title = title
    song.artist = "Generated by Guitar AI Assistant"
    song.tempo = max(30, min(260, int(round(float(bpm)))))
    song.tempoName = "Practice"
    song.tracks[0].name = "Rhythm Guitar" + (f" — Capo {capo}" if capo else "")
    song.tracks[0].offset = capo
    song.instructions = (
        f"Capo: fret {capo}. Chord names in tablature are the shapes to play."
        if capo else "No capo."
    )
    song.tracks[0].channel.instrument = 25
    song.tracks[0].settings.showRhythm = True
    _ensure_measures(song, len(chords), meter)
    pattern = strumming_pattern(float(bpm), meter, style)
    if meter == "4/4":
        dur, slots = models.Duration.eighth, 8
    elif meter in ("3/4", "6/8"):
        dur, slots = models.Duration.eighth, 6
    else:
        dur, slots = models.Duration.eighth, 8
    dir_by_step = {s: d for s, d in pattern["steps"]}
    for mi, chord in enumerate(tab_chords):
        measure = song.tracks[0].measures[mi]
        voice = measure.voices[0]
        voice.beats.clear()
        step_time = models.Duration(dur).time
        for step in range(slots):
            start = measure.start + step * step_time
            direction = dir_by_step.get(step)
            _add_chord_beat(voice, start, dur, chord, direction=direction, rest=(direction is None))
    guitarpro.write(song, out_path, version=(5, 1, 0))
    return out_path


@dataclass
class MelodyEvent:
    start: float
    end: float
    pitch: int
    velocity: int
    string: int = 0
    fret: int = 0


def _candidate_positions(pitch: int, max_fret: int = 20):
    out = []
    for string_num, open_note in enumerate(TUNING, start=1):
        fret = int(pitch) - open_note
        if 0 <= fret <= max_fret:
            out.append((string_num, fret))
    return out


def _group_midi_notes(notes, cluster_window: float):
    groups = []
    cur = []
    anchor = None
    for n in sorted(notes, key=lambda x: (x.start, -x.velocity, -x.pitch)):
        if anchor is None or n.start - anchor <= cluster_window:
            cur.append(n)
            if anchor is None:
                anchor = n.start
        else:
            groups.append(cur)
            cur = [n]
            anchor = n.start
    if cur:
        groups.append(cur)
    return groups


def _select_melody_from_groups(groups):
    """Choose one lead note per onset group with continuity-aware dynamic programming.

    This deliberately rejects the old behavior of turning every simultaneous Basic Pitch
    note into a chord. For a melody/lead transcription we want one coherent voice.
    """
    if not groups:
        return []

    cands = []
    for group in groups:
        by_pitch = {}
        for n in group:
            if not (40 <= int(n.pitch) <= 88):  # standard guitar through fret 24
                continue
            dur = max(0.02, float(n.end - n.start))
            prev = by_pitch.get(int(n.pitch))
            score = (dur, int(n.velocity))
            if prev is None or score > (prev[1], prev[2]):
                by_pitch[int(n.pitch)] = (n, dur, int(n.velocity))
        row = []
        for pitch, (n, dur, vel) in by_pitch.items():
            # duration + velocity matter most; tiny high-voice bias helps melody over bass/chord roots
            local_reward = min(dur, 2.0) * 0.75 + (vel / 127.0) * 0.9 + ((pitch - 40) / 48.0) * 0.08
            row.append((pitch, n, local_reward))
        if row:
            cands.append(row)

    if not cands:
        return []

    dp = []
    back = []
    for i, row in enumerate(cands):
        scores = [-1e18] * len(row)
        prev_idx = [-1] * len(row)
        if i == 0:
            for j, (_, _, reward) in enumerate(row):
                scores[j] = reward
        else:
            prev_row = cands[i - 1]
            prev_scores = dp[-1]
            for j, (pitch, n, reward) in enumerate(row):
                best = -1e18
                best_k = -1
                for k, (ppitch, pn, _) in enumerate(prev_row):
                    jump = abs(pitch - ppitch)
                    gap = max(0.0, float(n.start - pn.start))
                    transition = 0.075 * jump
                    if jump > 12:
                        transition += 0.12 * (jump - 12)
                    if gap < 0.09 and jump > 7:
                        transition += 0.7
                    val = prev_scores[k] + reward - transition
                    if val > best:
                        best, best_k = val, k
                scores[j] = best
                prev_idx[j] = best_k
        dp.append(scores)
        back.append(prev_idx)

    j = max(range(len(dp[-1])), key=lambda x: dp[-1][x])
    chosen = []
    for i in range(len(cands) - 1, -1, -1):
        pitch, n, _ = cands[i][j]
        chosen.append(MelodyEvent(float(n.start), float(n.end), int(pitch), int(n.velocity)))
        j = back[i][j] if i > 0 else -1
    chosen.reverse()

    # Remove implausibly tiny duplicates and prevent overlaps between consecutive melody notes.
    cleaned = []
    for ev in chosen:
        if cleaned and ev.start - cleaned[-1].start < 0.045 and ev.pitch == cleaned[-1].pitch:
            cleaned[-1].end = max(cleaned[-1].end, ev.end)
            continue
        cleaned.append(ev)
    for i in range(len(cleaned) - 1):
        cleaned[i].end = min(cleaned[i].end, cleaned[i + 1].start)
        if cleaned[i].end <= cleaned[i].start:
            cleaned[i].end = cleaned[i].start + 0.05
    return cleaned


def _assign_guitar_positions(events, max_fret: int = 20):
    if not events:
        return events
    rows = []
    for ev in events:
        positions = _candidate_positions(ev.pitch, max_fret=max_fret)
        if not positions:
            positions = _candidate_positions(ev.pitch, max_fret=24)
        if not positions:
            rows.append([])
        else:
            rows.append(positions)

    dp = []
    back = []
    for i, positions in enumerate(rows):
        if not positions:
            dp.append([]); back.append([]); continue
        scores = [1e18] * len(positions)
        prev_idx = [-1] * len(positions)
        if i == 0 or not dp[i - 1]:
            for j, (s, f) in enumerate(positions):
                scores[j] = 0.05 * f + 0.08 * abs(f - 7)
        else:
            prev_positions = rows[i - 1]
            prev_scores = dp[i - 1]
            for j, (s, f) in enumerate(positions):
                best, best_k = 1e18, -1
                for k, (ps, pf) in enumerate(prev_positions):
                    cost = prev_scores[k]
                    cost += 0.78 * abs(f - pf)
                    cost += 0.42 * abs(s - ps)
                    cost += 0.035 * f
                    if abs(f - pf) > 7:
                        cost += 0.6
                    if f == 0 and pf > 8:
                        cost += 0.3
                    if cost < best:
                        best, best_k = cost, k
                scores[j], prev_idx[j] = best, best_k
        dp.append(scores); back.append(prev_idx)

    # Backtrack per contiguous valid segment.
    i = len(events) - 1
    while i >= 0:
        while i >= 0 and not rows[i]:
            i -= 1
        if i < 0:
            break
        end = i
        start = i
        while start > 0 and rows[start - 1]:
            start -= 1
        j = min(range(len(dp[end])), key=lambda x: dp[end][x])
        for k in range(end, start - 1, -1):
            s, f = rows[k][j]
            events[k].string, events[k].fret = int(s), int(f)
            j = back[k][j] if k > start else -1
        i = start - 1
    return events


def extract_melody_events(midi_path, bpm, max_seconds=180):
    import pretty_midi
    pm = pretty_midi.PrettyMIDI(midi_path)
    notes = []
    for inst in pm.instruments:
        if inst.is_drum:
            continue
        for n in inst.notes:
            if n.start <= max_seconds and n.end - n.start >= 0.035:
                notes.append(n)
    if not notes:
        raise ValueError("No pitched notes found in Basic Pitch MIDI")
    bpm = max(40.0, min(240.0, float(bpm or 120)))
    sixteenth = 60.0 / bpm / 4.0
    groups = _group_midi_notes(notes, cluster_window=max(0.035, sixteenth * 0.55))
    events = _select_melody_from_groups(groups)
    events = _assign_guitar_positions(events)
    return [e for e in events if e.string > 0]


def _slots_per_bar(meter: str):
    if meter == "4/4":
        return 16
    if meter in ("3/4", "6/8"):
        return 12
    try:
        num, den = [int(x) for x in meter.split("/")]
        return max(4, int(round(num * 16 / den)))
    except Exception:
        return 16


def build_melody_gp5(midi_path, bpm, meter, out_path, title="Video Melody Transcription", max_seconds=180):
    events = extract_melody_events(midi_path, bpm, max_seconds=max_seconds)
    if not events:
        raise ValueError("Could not extract a coherent melody line")

    bpm = max(40.0, min(240.0, float(bpm or 120)))
    meter = meter if meter in ("4/4", "3/4", "6/8") else "4/4"
    sixteenth_sec = 60.0 / bpm / 4.0
    slots_bar = _slots_per_bar(meter)

    # Quantize event boundaries and truncate a note at the next onset.
    q = []
    for i, ev in enumerate(events):
        start_slot = max(0, int(round(ev.start / sixteenth_sec)))
        raw_end = max(start_slot + 1, int(round(ev.end / sixteenth_sec)))
        if i + 1 < len(events):
            next_slot = max(start_slot + 1, int(round(events[i + 1].start / sixteenth_sec)))
            raw_end = min(raw_end, next_slot)
        q.append((start_slot, max(start_slot + 1, raw_end), ev))

    last_slot = max(end for _, end, _ in q)
    measures = max(1, int(math.ceil(last_slot / slots_bar)))

    song = models.Song()
    song.title = title
    song.artist = "Automatic lead/melody transcription — verify by ear"
    song.tempo = int(round(bpm))
    song.tempoName = "Detected tempo"
    song.instructions = "Melody/lead extraction from Basic Pitch MIDI. Standard tuning E A D G B E. No capo assumed."
    track = song.tracks[0]
    track.name = "Lead / Melody Guitar"
    track.channel.instrument = 25
    track.settings.showRhythm = True
    _ensure_measures(song, measures, meter)

    slot_map = {}
    for start, end, ev in q:
        for slot in range(start, end):
            slot_map[slot] = (ev, slot == start)

    dur = models.Duration.sixteenth
    dur_time = models.Duration(dur).time
    for mi in range(measures):
        measure = track.measures[mi]
        voice = measure.voices[0]
        voice.beats.clear()
        for local in range(slots_bar):
            global_slot = mi * slots_bar + local
            beat = models.Beat(voice)
            beat.start = measure.start + local * dur_time
            beat.duration = models.Duration(dur)
            item = slot_map.get(global_slot)
            if item is None:
                beat.status = models.BeatStatus.rest
            else:
                ev, is_start = item
                beat.status = models.BeatStatus.normal
                ntype = models.NoteType.normal if is_start else models.NoteType.tie
                beat.notes.append(
                    models.Note(
                        beat,
                        value=int(ev.fret),
                        string=int(ev.string),
                        type=ntype,
                    )
                )
            voice.beats.append(beat)

    guitarpro.write(song, out_path, version=(5, 1, 0))
    return events


def write_melody_tab_txt(events, out_path, title="Melody TAB"):
    names = ["e", "B", "G", "D", "A", "E"]
    lines = [title, "Standard tuning: E A D G B E", ""]
    if not events:
        lines.append("No melody events detected.")
        Path(out_path).write_text("\n".join(lines), encoding="utf-8")
        return out_path

    chunk = 16
    for base in range(0, len(events), chunk):
        block = events[base:base + chunk]
        t0 = block[0].start
        mm, ss = divmod(int(t0), 60)
        lines.append(f"[{mm:02d}:{ss:02d}]")
        for sidx, name in enumerate(names, start=1):
            row = name + "|"
            for ev in block:
                token = f"{ev.fret}" if ev.string == sidx else ""
                row += token.center(4, "-")
            row += "|"
            lines.append(row)
        lines.append("")
    Path(out_path).write_text("\n".join(lines), encoding="utf-8")
    return out_path


# Kept for backwards compatibility. In V3 this is explicitly a raw/polyphonic conversion,
# not the preferred melody transcription path.
def build_tab_from_midi(midi_path, bpm, out_path, title="Raw MIDI Transcription", max_seconds=180):
    import pretty_midi
    pm = pretty_midi.PrettyMIDI(midi_path)
    notes = []
    for inst in pm.instruments:
        if inst.is_drum:
            continue
        notes.extend(inst.notes)
    notes = [n for n in notes if n.start <= max_seconds]
    notes.sort(key=lambda n: n.start)
    bpm = max(40, min(240, float(bpm or 120)))
    sixteenth = 60.0 / bpm / 4.0
    slots = {}
    for n in notes:
        idx = int(round(n.start / sixteenth))
        slots.setdefault(idx, []).append(n.pitch)
    max_slot = max(slots.keys(), default=0)
    measures = max(1, max_slot // 16 + 1)

    song = models.Song()
    song.title = title
    song.artist = "Raw automatic transcription — verify by ear"
    song.tempo = int(round(bpm))
    song.tracks[0].name = "Raw detected notes"
    song.tracks[0].channel.instrument = 25
    _ensure_measures(song, measures, "4/4")
    prev_fret = 5
    for mi in range(measures):
        measure = song.tracks[0].measures[mi]
        voice = measure.voices[0]
        voice.beats.clear()
        for local in range(16):
            idx = mi * 16 + local
            beat = models.Beat(voice)
            beat.start = measure.start + local * models.Duration(models.Duration.sixteenth).time
            beat.duration = models.Duration(models.Duration.sixteenth)
            pitches = sorted(set(slots.get(idx, [])))
            if pitches:
                beat.status = models.BeatStatus.normal
                used = set()
                for pitch in pitches[:6]:
                    choices = []
                    for s, open_note in enumerate(TUNING, start=1):
                        fret = pitch - open_note
                        if 0 <= fret <= 24 and s not in used:
                            choices.append((abs(fret - prev_fret) + 0.12 * fret, s, fret))
                    if choices:
                        _, s, f = min(choices)
                        used.add(s)
                        prev_fret = f
                        beat.notes.append(models.Note(beat, value=int(f), string=int(s), type=models.NoteType.normal))
            else:
                beat.status = models.BeatStatus.rest
            voice.beats.append(beat)
    guitarpro.write(song, out_path, version=(5, 1, 0))
    return out_path
